#!/bin/bash
3
4 # Fungsi untuk clear terminal dan memaparkan gambar
5 function clear {
6     # Lokasi gambar
7     IMAGE_PATH="storage/to/img.jpg " # Tukar dengan laluan gambar anda
8
9     # Kosongkan terminal
10     command clear
11
12     # Paparkan gambar dengan catimg
13     catimg "$IMAGE_PATH"
14 }
15
16 # Alias untuk memastikan fungsi digunakan setiap kali 'clear' dipanggil
17 alias clear=clear